[package]
name = "fuzzy"
version = "0.1.0"
authors = ["Chenjox"]
edition = "2021"

[dependencies]
libm = { version = "0.2.5" }
argmin = { version = "0.7" }
argmin-math = { version = "0.2", features = ["nalgebra_v0_31"] }
nalgebra = { version = "0.31.1" }
