[package]
name = "fuzzy"
version = "0.1.0"
authors = ["Chenjox"]
edition = "2021"

[dependencies]
libm = { version = "0.2.5" }
nalgebra = { version = "0.31.1" }
rand = { version = "0.8.5" }
rand_distr = { version = "0.4.3" }

[dev-dependencies]
assert_approx_eq = "1.1.0"
