[package]
name = "gui"
version = "0.1.0"
authors = ["Chenjox"]
edition = "2021"

[dependencies]
iced = { version = "0.4.2", features =["pure"]}
env_logger = "0.8"
nalgebra = { version = "0.31.1" }
structmech = { path = "../structmech" }
fuzzy = { path = "../fuzzy" }

[profile.dev]
opt-level = 1
